package com.marcelandrejko.m.nameday;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;

/**
 * Created by nd on 04.12.2017.
 */

public class SlovakCalendar {

    private final java.util.Map<String, String> calendar = new HashMap<String, String>();

    private java.text.DateFormat df = new SimpleDateFormat("MM dd");

    public String get(Date d) {
        String key = this.df.format(d);
        if (this.calendar.containsKey(key))
            return (String)this.calendar.get(key);
        return "";
    }

    public String getCurrent() {
        return this.get(Calendar.getInstance().getTime());
    }

    public SlovakCalendar() {
        this.calendar.put("01 02", "Alexandra, Karina");
        this.calendar.put("01 03", "Daniela");
        this.calendar.put("01 04", "Drahoslav");
        this.calendar.put("01 05", "Andrea");
        this.calendar.put("01 06", "Antónia");
        this.calendar.put("01 07", "Bohuslava");
        this.calendar.put("01 08", "Severín");
        this.calendar.put("01 09", "Alexej");
        this.calendar.put("01 10", "Dáša");
        this.calendar.put("01 11", "Malvína");
        this.calendar.put("01 12", "Ernest");
        this.calendar.put("01 13", "Rastislav");
        this.calendar.put("01 14", "Radovan");
        this.calendar.put("01 15", "Dobroslav");
        this.calendar.put("01 16", "Kristína");
        this.calendar.put("01 17", "Nataša");
        this.calendar.put("01 18", "Bohdana");
        this.calendar.put("01 19", "Drahomíra, Mário");
        this.calendar.put("01 20", "Dalibor");
        this.calendar.put("01 21", "Vincent");
        this.calendar.put("01 22", "Zora");
        this.calendar.put("01 23", "Miloš");
        this.calendar.put("01 24", "Timotej");
        this.calendar.put("01 25", "Gejza");
        this.calendar.put("01 26", "Tamara");
        this.calendar.put("01 27", "Bohuš");
        this.calendar.put("01 28", "Alfonz");
        this.calendar.put("01 29", "Gašpar");
        this.calendar.put("01 30", "Ema");
        this.calendar.put("01 31", "Emil");
        this.calendar.put("02 01", "Tatiana");
        this.calendar.put("02 02", "Erika, Erik");
        this.calendar.put("02 03", "Blažej");
        this.calendar.put("02 04", "Veronika");
        this.calendar.put("02 05", "Agáta");
        this.calendar.put("02 06", "Dorota");
        this.calendar.put("02 07", "Vanda");
        this.calendar.put("02 08", "Zoja");
        this.calendar.put("02 09", "Zdenko");
        this.calendar.put("02 10", "Gabriela");
        this.calendar.put("02 11", "Dezider");
        this.calendar.put("02 12", "Perla");
        this.calendar.put("02 13", "Arpád");
        this.calendar.put("02 14", "Valentín");
        this.calendar.put("02 15", "Pravoslav");
        this.calendar.put("02 16", "Ida, Liana");
        this.calendar.put("02 17", "Miloslava");
        this.calendar.put("02 18", "Jaromír");
        this.calendar.put("02 19", "Vlasta");
        this.calendar.put("02 20", "Lívia");
        this.calendar.put("02 21", "Eleonóra");
        this.calendar.put("02 22", "Etela");
        this.calendar.put("02 23", "Roman, Romana");
        this.calendar.put("02 24", "Matej");
        this.calendar.put("02 25", "Frederik, Frederika");
        this.calendar.put("02 26", "Viktor");
        this.calendar.put("02 27", "Alexander");
        this.calendar.put("02 28", "Zlatica");
        this.calendar.put("03 01", "Albín");
        this.calendar.put("03 02", "Anežka");
        this.calendar.put("03 03", "Bohumil, Bohumila");
        this.calendar.put("03 04", "Kazimír");
        this.calendar.put("03 05", "Fridrich");
        this.calendar.put("03 06", "Radoslav, Radoslava");
        this.calendar.put("03 07", "Tomáš");
        this.calendar.put("03 08", "Alan, Alana");
        this.calendar.put("03 09", "Františka");
        this.calendar.put("03 10", "Bruno, Branislav");
        this.calendar.put("03 11", "Angela, Angelika");
        this.calendar.put("03 12", "Gregor");
        this.calendar.put("03 13", "Vlastimil");
        this.calendar.put("03 14", "Matilda");
        this.calendar.put("03 15", "Svetlana");
        this.calendar.put("03 16", "Boleslav");
        this.calendar.put("03 17", "Lubica");
        this.calendar.put("03 18", "Eduard");
        this.calendar.put("03 19", "Jozef");
        this.calendar.put("03 20", "Vítazoslav, Klaudius");
        this.calendar.put("03 21", "Blahoslav");
        this.calendar.put("03 22", "Benadik");
        this.calendar.put("03 23", "Adrián");
        this.calendar.put("03 24", "Gabriel");
        this.calendar.put("03 25", "Marián");
        this.calendar.put("03 26", "Emanuel");
        this.calendar.put("03 27", "Alena");
        this.calendar.put("03 28", "Sona");
        this.calendar.put("03 29", "Miroslav");
        this.calendar.put("03 30", "Vieroslava");
        this.calendar.put("03 31", "Benjamín");
        this.calendar.put("04 01", "Hugo");
        this.calendar.put("04 02", "Zita");
        this.calendar.put("04 03", "Richard");
        this.calendar.put("04 04", "Izidor");
        this.calendar.put("04 05", "Miroslava");
        this.calendar.put("04 06", "Irena");
        this.calendar.put("04 07", "Zoltán");
        this.calendar.put("04 08", "Albert");
        this.calendar.put("04 09", "Milena");
        this.calendar.put("04 10", "Igor");
        this.calendar.put("04 11", "Július");
        this.calendar.put("04 12", "Estera");
        this.calendar.put("04 13", "Aleš");
        this.calendar.put("04 14", "Justina");
        this.calendar.put("04 15", "Fedor");
        this.calendar.put("04 16", "Dana, Danica");
        this.calendar.put("04 17", "Rudolf, Rudolfa");
        this.calendar.put("04 18", "Valér");
        this.calendar.put("04 19", "Jela");
        this.calendar.put("04 20", "Marcel");
        this.calendar.put("04 21", "Ervín");
        this.calendar.put("04 22", "Slavomír");
        this.calendar.put("04 23", "Vojtech");
        this.calendar.put("04 24", "Juraj");
        this.calendar.put("04 25", "Marek");
        this.calendar.put("04 26", "Jaroslava");
        this.calendar.put("04 27", "Jaroslav");
        this.calendar.put("04 28", "Jarmila");
        this.calendar.put("04 29", "Lea");
        this.calendar.put("04 30", "Anastázia");
        this.calendar.put("05 02", "Žigmund");
        this.calendar.put("05 03", "Galina, Timea");
        this.calendar.put("05 04", "Florián");
        this.calendar.put("05 05", "Lesia, Lesana");
        this.calendar.put("05 06", "Hermína");
        this.calendar.put("05 07", "Monika");
        this.calendar.put("05 08", "Ingrida");
        this.calendar.put("05 09", "Roland");
        this.calendar.put("05 10", "Viktória");
        this.calendar.put("05 11", "Blažena");
        this.calendar.put("05 12", "Pankrác");
        this.calendar.put("05 13", "Servác");
        this.calendar.put("05 14", "Bonifác");
        this.calendar.put("05 15", "Žofia, Sofia");
        this.calendar.put("05 16", "Svetozár");
        this.calendar.put("05 17", "Gizela, Aneta");
        this.calendar.put("05 18", "Viola");
        this.calendar.put("05 19", "Gertrúda");
        this.calendar.put("05 20", "Bernard");
        this.calendar.put("05 21", "Zina");
        this.calendar.put("05 22", "Júlia, Juliana");
        this.calendar.put("05 23", "Želmíra");
        this.calendar.put("05 24", "Ela");
        this.calendar.put("05 25", "Urban, Vivien");
        this.calendar.put("05 26", "Dušan");
        this.calendar.put("05 27", "Iveta");
        this.calendar.put("05 28", "Viliam");
        this.calendar.put("05 29", "Vilma");
        this.calendar.put("05 30", "Ferdinand");
        this.calendar.put("05 31", "Petrana, Petronela");
        this.calendar.put("06 01", "Žaneta");
        this.calendar.put("06 02", "Xénia, Oxana");
        this.calendar.put("06 03", "Karolína");
        this.calendar.put("06 04", "Lenka");
        this.calendar.put("06 05", "Laura");
        this.calendar.put("06 06", "Norbert");
        this.calendar.put("06 07", "Róbert, Róberta");
        this.calendar.put("06 08", "Medard");
        this.calendar.put("06 09", "Stanislava");
        this.calendar.put("06 10", "Margaréta, Gréta");
        this.calendar.put("06 11", "Dobroslava");
        this.calendar.put("06 12", "Zlatko");
        this.calendar.put("06 13", "Anton");
        this.calendar.put("06 14", "Vasil");
        this.calendar.put("06 15", "Vít");
        this.calendar.put("06 16", "Blanka, Bianka");
        this.calendar.put("06 17", "Adolf");
        this.calendar.put("06 18", "Vratislav");
        this.calendar.put("06 19", "Alfréd");
        this.calendar.put("06 20", "Valéria");
        this.calendar.put("06 21", "Alojz");
        this.calendar.put("06 22", "Paulína");
        this.calendar.put("06 23", "Sidónia");
        this.calendar.put("06 24", "Ján");
        this.calendar.put("06 25", "Olívia, Tadeáš");
        this.calendar.put("06 26", "Adriána");
        this.calendar.put("06 27", "Ladislav, Ladislava");
        this.calendar.put("06 28", "Beáta");
        this.calendar.put("06 29", "Peter, Pavol, Petra");
        this.calendar.put("06 30", "Melánia");
        this.calendar.put("07 01", "Diana");
        this.calendar.put("07 02", "Berta");
        this.calendar.put("07 03", "Miloslav");
        this.calendar.put("07 04", "Prokop");
        this.calendar.put("07 05", "Cyril, Metod");
        this.calendar.put("07 06", "Patrik, Patrícia");
        this.calendar.put("07 07", "Oliver");
        this.calendar.put("07 08", "Ivan");
        this.calendar.put("07 09", "Lujza");
        this.calendar.put("07 10", "Amália");
        this.calendar.put("07 11", "Milota");
        this.calendar.put("07 12", "Nina");
        this.calendar.put("07 13", "Margita");
        this.calendar.put("07 14", "Kamil");
        this.calendar.put("07 15", "Henrich");
        this.calendar.put("07 16", "Drahomír, Rút");
        this.calendar.put("07 17", "Bohuslav");
        this.calendar.put("07 18", "Kamila");
        this.calendar.put("07 19", "Dušana");
        this.calendar.put("07 20", "Ilja, Eliáš");
        this.calendar.put("07 21", "Daniel");
        this.calendar.put("07 22", "Magdaléna");
        this.calendar.put("07 23", "Olga");
        this.calendar.put("07 24", "Vladimír");
        this.calendar.put("07 25", "Jakub, Timur");
        this.calendar.put("07 26", "Anna, Hana, Anita");
        this.calendar.put("07 27", "Božena");
        this.calendar.put("07 28", "Krištof");
        this.calendar.put("07 29", "Marta");
        this.calendar.put("07 30", "Libuša");
        this.calendar.put("07 31", "Ignác");
        this.calendar.put("08 01", "Božidara");
        this.calendar.put("08 02", "Gustáv");
        this.calendar.put("08 03", "Jerguš");
        this.calendar.put("08 04", "Dominika, Dominik");
        this.calendar.put("08 05", "Hortenzia");
        this.calendar.put("08 06", "Jozefína");
        this.calendar.put("08 07", "Štefánia");
        this.calendar.put("08 08", "Oskar");
        this.calendar.put("08 09", "Lubomíra");
        this.calendar.put("08 10", "Vavrinec");
        this.calendar.put("08 11", "Zuzana");
        this.calendar.put("08 12", "Darina");
        this.calendar.put("08 13", "Lubomír");
        this.calendar.put("08 14", "Mojmír");
        this.calendar.put("08 15", "Marcela");
        this.calendar.put("08 16", "Leonard");
        this.calendar.put("08 17", "Milica");
        this.calendar.put("08 18", "Elena, Helena");
        this.calendar.put("08 19", "Lýdia");
        this.calendar.put("08 20", "Anabela, Liliana");
        this.calendar.put("08 21", "Jana");
        this.calendar.put("08 22", "Tichomír");
        this.calendar.put("08 23", "Filip");
        this.calendar.put("08 24", "Bartolomej");
        this.calendar.put("08 25", "Ludovít");
        this.calendar.put("08 26", "Samuel");
        this.calendar.put("08 27", "Silvia");
        this.calendar.put("08 28", "Augustín");
        this.calendar.put("08 29", "Nikola, Nikolaj");
        this.calendar.put("08 30", "Ružena");
        this.calendar.put("08 31", "Nora");
        this.calendar.put("09 01", "Drahoslava");
        this.calendar.put("09 02", "Linda, Rebeka");
        this.calendar.put("09 03", "Belo");
        this.calendar.put("09 04", "Rozália");
        this.calendar.put("09 05", "Regina");
        this.calendar.put("09 06", "Alica");
        this.calendar.put("09 07", "Marianna");
        this.calendar.put("09 08", "Miriama");
        this.calendar.put("09 09", "Martina");
        this.calendar.put("09 10", "Oleg");
        this.calendar.put("09 11", "Bystrík");
        this.calendar.put("09 12", "Mária, Marlena");
        this.calendar.put("09 13", "Ctibor");
        this.calendar.put("09 14", "Ludomil");
        this.calendar.put("09 15", "Jolana");
        this.calendar.put("09 16", "Ludmila");
        this.calendar.put("09 17", "Olympia");
        this.calendar.put("09 18", "Eugénia");
        this.calendar.put("09 19", "Konštantín");
        this.calendar.put("09 20", "Luboslav, Luboslava");
        this.calendar.put("09 21", "Matúš");
        this.calendar.put("09 22", "Móric");
        this.calendar.put("09 23", "Zdenka");
        this.calendar.put("09 24", "Luboš, Lubor");
        this.calendar.put("09 25", "Vladislav, Vladislava");
        this.calendar.put("09 26", "Edita");
        this.calendar.put("09 27", "Cyprián");
        this.calendar.put("09 28", "Václav");
        this.calendar.put("09 29", "Michal, Michaela");
        this.calendar.put("09 30", "Jarolím");
        this.calendar.put("10 01", "Arnold");
        this.calendar.put("10 02", "Levoslav");
        this.calendar.put("10 03", "Stela");
        this.calendar.put("10 04", "František");
        this.calendar.put("10 05", "Viera");
        this.calendar.put("10 06", "Natália");
        this.calendar.put("10 07", "Eliška");
        this.calendar.put("10 08", "Brigita");
        this.calendar.put("10 09", "Dionýz");
        this.calendar.put("10 10", "Slavomíra");
        this.calendar.put("10 11", "Valentína");
        this.calendar.put("10 12", "Maximilián");
        this.calendar.put("10 13", "Koloman");
        this.calendar.put("10 14", "Boris");
        this.calendar.put("10 15", "Terézia");
        this.calendar.put("10 16", "Vladimíra");
        this.calendar.put("10 17", "Hedviga");
        this.calendar.put("10 18", "Lukáš");
        this.calendar.put("10 19", "Kristián");
        this.calendar.put("10 20", "Vendelín");
        this.calendar.put("10 21", "Uršula");
        this.calendar.put("10 22", "Sergej");
        this.calendar.put("10 23", "Alojzia");
        this.calendar.put("10 24", "Kvetoslava");
        this.calendar.put("10 25", "Aurel");
        this.calendar.put("10 26", "Demeter");
        this.calendar.put("10 27", "Sabína");
        this.calendar.put("10 28", "Dobromila");
        this.calendar.put("10 29", "Klára");
        this.calendar.put("10 30", "Šimon, Simona");
        this.calendar.put("10 31", "Aurélia");
        this.calendar.put("11 01", "Denis, Denisa");
        this.calendar.put("11 03", "Hubert");
        this.calendar.put("11 04", "Karol");
        this.calendar.put("11 05", "Imrich");
        this.calendar.put("11 06", "Renáta");
        this.calendar.put("11 07", "René");
        this.calendar.put("11 08", "Bohumír");
        this.calendar.put("11 09", "Teodor");
        this.calendar.put("11 10", "Tibor");
        this.calendar.put("11 11", "Martin, Maroš");
        this.calendar.put("11 12", "Svätopluk");
        this.calendar.put("11 13", "Stanislav");
        this.calendar.put("11 14", "Irma");
        this.calendar.put("11 15", "Leopold");
        this.calendar.put("11 16", "Agnesa");
        this.calendar.put("11 17", "Klaudia");
        this.calendar.put("11 18", "Eugen");
        this.calendar.put("11 19", "Alžbeta");
        this.calendar.put("11 20", "Félix");
        this.calendar.put("11 21", "Elvíra");
        this.calendar.put("11 22", "Cecília");
        this.calendar.put("11 23", "Klement");
        this.calendar.put("11 24", "Emília");
        this.calendar.put("11 25", "Katarína");
        this.calendar.put("11 26", "Kornel");
        this.calendar.put("11 27", "Milan");
        this.calendar.put("11 28", "Henrieta");
        this.calendar.put("11 29", "Vratko");
        this.calendar.put("11 30", "Ondrej, Andrej");
        this.calendar.put("12 01", "Edmund");
        this.calendar.put("12 02", "Bibiána");
        this.calendar.put("12 03", "Oldrich");
        this.calendar.put("12 04", "Barbora, Barbara");
        this.calendar.put("12 05", "Oto");
        this.calendar.put("12 06", "Mikuláš");
        this.calendar.put("12 07", "Ambróz");
        this.calendar.put("12 08", "Marína");
        this.calendar.put("12 09", "Izabela");
        this.calendar.put("12 10", "Radúz");
        this.calendar.put("12 11", "Hilda");
        this.calendar.put("12 12", "Otília");
        this.calendar.put("12 13", "Lucia");
        this.calendar.put("12 14", "Branislava, Bronislava");
        this.calendar.put("12 15", "Ivica");
        this.calendar.put("12 16", "Albína");
        this.calendar.put("12 17", "Kornélia");
        this.calendar.put("12 18", "Sláva");
        this.calendar.put("12 19", "Judita");
        this.calendar.put("12 20", "Dagmara");
        this.calendar.put("12 21", "Bohdan");
        this.calendar.put("12 22", "Adela");
        this.calendar.put("12 23", "Nadežda");
        this.calendar.put("12 24", "Adam, Eva");
        this.calendar.put("12 26", "Štefan");
        this.calendar.put("12 27", "Filoména");
        this.calendar.put("12 28", "Ivana, Ivona");
        this.calendar.put("12 29", "Milada");
        this.calendar.put("12 30", "Dávid");
        this.calendar.put("12 31", "Silvester");
    }
}
